services:
  - type: worker
    name: telegram-bot
    runtime: python
    repo: https://github.com/wrath0504/telegram-bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
